application: where-is-curtis
version: 1
runtime: go
api_version: go1

handlers:
- url: /$
  static_files: app/build/bundled/index.html
  upload: app/build/bundled/index.html
  secure: always 

- url: /shared-bundle.html
  static_files: app/build/bundled/shared-bundle.html
  upload: app/build/bundled/shared-bundle.html
  secure: always 

- url: /layers
  static_dir: layers
  mime_type: application/vnd.google-earth.kmz

- url: /.*
  script: _go_app
  secure: always